### ISSUE TITLE
Function not working concurrently

### ISSUE THREAD

**Issue by factormaarten** [recoilphp/recoil#162]
Hi there,

I'm new to recoil and using it with React. I'm trying to run functions concurrently, not synchronously.

This is my code to test:

```
    public function execute($json)
    {
        $loop = Factory::create();
        $kernel = ReactKernel::create($loop);

        $kernel->execute(function () {
            yield [
                $this->fetchTrade(1),
                $this->fetchTrade(2),
                $this->fetchTrade(3),
            ];
        });

        $loop->run();
    }

    private function fetchTrade($id) {
        echo $id . PHP_EOL;
        sleep(1);
        yield;
        return;
    }
```

Unfortunately the code runs synchronously and not concurrently (the sleep is called after each execution). How do I correct this code so it does work concurrently like in the example?

Thanks so much,
Maarten

**Comment by jmalloc** [comment]
Hi, if I understand correctly, the issue is the call to the standard `sleep()`. Instead, use [`Recoil::sleep()`](https://github.com/recoilphp/api/blob/master/src/Recoil.php#L154) which is "cooperative", allowing the other strands to execute in the meantime:

```php
use Recoil\Recoil;

public function execute($json)
{
    $loop = Factory::create();
    $kernel = ReactKernel::create($loop);

    $kernel->execute(function () {
        yield [
            $this->fetchTrade(1),
            $this->fetchTrade(2),
            $this->fetchTrade(3),
        ];
    });

    $loop->run();
}

private function fetchTrade($id) {
    echo $id . PHP_EOL;
    yield Recoil::sleep(1);
}
```

This should produce the same output, but the program will only wait for ~1 second overall. 

Let me know if this helps :)

**Comment by mpjraaij** [comment]
That does indeed help a bit..

However I was not aware that the sleep() function is the standard.. I replaced that with a function that takes 2 seconds to execute.. how can I add concurrent behaviour to any function?

I'm using recoil/react and have access to creating promises in react.. would I have to create a promise for it to concurrently work with recoil?

**Comment by jmalloc** [comment]
> would I have to translate the fetchTrade function into a concurrent coroutine?

Yep, this is the key. Tools like Recoil, React, etc can't make code that isn't already asynchronous execute concurrently. Nor do they allow for any kind of parallelism (there's still only ever one actual OS thread). 

If you take a look through the [Recoil class](https://github.com/recoilphp/api/blob/master/src/Recoil.php) you'll see that some of the operations are categorised as either `COOPERATIVE` or `NON-COOPERATIVE`. These cooperative operations "cooperate" by giving control to the Recoil kernel to do other work while the operation executes. Note that all such operations wait on some event to occur, such as waking from a sleep or for a stream to become readable. All we're really doing is making sure we're able to use CPU to do something useful while we wait for these events.

If `fetchTrade()` were CPU bound, there'd be no advantage to using an asynchronous framework, because there would be none of these events to wait for. Assuming, however, that `fetchTrade()` makes a HTTP request, we can allow the CPU to do something while it waits for the result by performing that network IO in a way that Recoil (well, React, really) is aware of - namely by using the `Recoil::read()` and `write()` operations on a network stream, or more practically using an HTTP client that's built for React (such as [Buzz](github.com/clue/reactphp-buzz)).

I hope this is helpful. Please keep the questions coming, and forgive me if some explanations are too basic, but this kind of question comes up often enough that I figure this info might be helpful to others, too.

---

As an aside, if you're going to write some code using Recoil-style coroutines (which of course I encourage!) I'd like to point out the existence of the [recoil/dev](https://github.com/recoilphp/dev) package. It's primary feature is an instrumentation system that re-writes stack traces inside exceptions to show the "yield points" in coroutines rather than the PHP code inside the Recoil kernel. 

This has proven invaluable for dealing with Recoil code in real projects. The instrumentation system is performed entirely within `assert()` statements, and so incurs no overhead in production where assertions are disabled.

There is [an example](https://github.com/recoilphp/dev/blob/master/examples) that shows the difference between the stack trace with the instrumentation enabled vs disabled. All it requires from your codebase is that you annotate functions that are intended as coroutines like so:

```php
use Generator as Coroutine; // important

function myGenerator(): Coroutine {
    yield Recoil::sleep(5);
}
```

**Comment by mpjraaij** [comment]
Thanks for the elaborate post! I'm determined to make this work with Recoil.

If I understand correctly, it works like this: (correct me where I'm wrong).

Anything that's CPU bound, like calculations, fetching from DB, etc. is non-cooperative and hence can't be done asynchronous. However if I make an API call to an external service, this can be done cooperative.

This means I could start fetching API calls async, and while I'm doing that have the system continue to do some CPU calculations (sync). And then when the calls are finished, save everything to the DB (sync).

This leaves me to these questions:
- What is exactly a strand? To me this sounds like a side-pice of code that's being executed.
- How exactly can I use the cooperate() function in the Kernel?

-----

I also see your point with the stack traces, I'd have to implement it in Phalcon. If I'm not mistaken this gets included AFTER the autoload include, am I right?

**Comment by mpjraaij** [comment]
Thank you so much for taking the time to explain this all!

I hope it will help others too.

I have indeed tried the MySQL bindings from ReactPHP, but have found that they're no faster than the Phalcon ORM (it's C-based and caches most), hence I might as well stick to what I know.

You've helped out a lot and I'm confident I can make it work now. Many many thanks.

**Comment by mpjraaij** [comment]
One more question that keeps haunting me. I have for example this piece of code:

```php
    private function getSingleTrade($id): Coroutine
    {
        $trade = Trades::findFirst([
            'conditions' => 'id = {id:int}',
            'bind' => [
                'id' => $id
            ]
        ]);

        yield;
        return $trade;
    }
```

When I then do `var_dump ($this->getSingleTrade($id))` I get this:

```
object(Generator)#119 (0) {
}
```

Why is the return not filled in the Generator?

**Comment by jmalloc** [comment]
> **I have indeed tried the MySQL bindings from ReactPHP, but have found that they're no faster than the Phalcon ORM**

They may not be faster for a given query but importantly they are cooperative, so you can run several queries concurrently, as well as any other kind of IO. This probably wont matter to you much if you're starting a kernel to perform a single task with a small concurrent aspect, but just remember *everything* else stops to wait for those blocking DB queries made by a conventional DBAL.

> **Why is the return not filled in the Generator?**

The return value of a generator function in PHP is always a `\Generator`, which is an iterator-like object that steps between the `yield` statements each time it is advanced. It's Recoil's job to step through that `\Generator` and interpret the things it yields as instructions. Recoil's terminology for these yielded things is ["dispatchable values"](https://github.com/recoilphp/api/blob/master/src/Recoil.php#L30).

Try this code, and you'll see how to access the values you're expecting directly from the `\Generator`:

```php
function blah() {
    yield "I am a yielded value!";
    return "I am the return value!";
}

$gen = blah();

foreach ($gen as $value) {
    echo $value . PHP_EOL;
}

echo $gen->getReturn() . PHP_EOL;
```

When you want to use a `\Generator` as a coroutine you need to give it Recoil for execution. The example below would dump the `Trade` object as you expect.

```php
function run() {
    $get = $o->getSingleTrade($id);
    var_dump(yield $get);
}

$run = run();
$kernel->execute($run);
```

I've assigned the generators to the variables `$run` and `$get` just so they have names we can refer to. Notice the `yield` in the `var_dump()` call above. This is what lets Recoil "see" `$get`.

The process goes something like this:
- Recoil starts iterating over `$run`
- sees the yielded `$get`, which it [decides to treat it as a coroutine](https://github.com/recoilphp/kernel/blob/ad07233480953b43889f999b0ae9164c1e8b3ae9/src/StrandTrait.php#L160)
- pushes `$get` onto the call-stack for the current strand and starts iterating over it instead
- (repeats this whole process for the things yielded from `$get`)
- reaches the end of `$get` and pops it from the call stack
- calls `$get->getReturn()` to get the `Trade`, which it [sends](http://php.net/manual/en/generator.send.php) back to `$run`
- continues iterating `$run`
- reaches the end of `$run` and terminates the strand

If you haven't already I'd recommend reading [this post](https://medium.com/async-php/co-operative-php-multitasking-ce4ef52858a0) by Christopher Pitt. It's a fantastic introduction to the ideas in play here from the very basics of iterators to the use of generators as coroutines.

**Comment by jmalloc** [comment]
I guess that depends on what you wan't to achieve there. Recoil is not involved in that code there is no coroutine, only "normal" generators. 

Note in the example you pasted you're only using the value of `getReturn()` from the last generator in the array. The code below produces the same output, and is "simpler" insofar as it uses only single generator.

```php
public function blah() {
    for ($i = 0; $i < 5; ++$i) {
            yield "I am a yielded value!";
    }

    return "I am the return value!";
}

public function run()
{
    $gen = $this->blah();

    foreach ($gen as $value) {
        echo $value . PHP_EOL;
    }

    echo $gen->getReturn() . PHP_EOL;
}
```
